import type { Metadata } from "next";
import { Inter, Righteous } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/shared/header/header";
import Footer from "@/components/shared/footer/footer";

const inter = Inter({ subsets: ["latin"] });

const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-righteous",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${righteous.variable} ${inter.className}`}>
        <Header />
        <main className="min-h-screen bg-milk-white  pt-[1.995rem] md:pt-[5.348rem]">
          <div className="bg-[url('/images/blocker.png')] bg-contain bg-[center_top_-8vw] bg-no-repeat">
            {children}
          </div>
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
