import type { Metadata } from "next";
import { Inter, Righteous } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-righteous",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${righteous.variable} ${inter.className}`}>
        <main className="min-h-screen bg-milk-white bg-[url('/images/blocker.png')] bg-contain bg-left-top bg-no-repeat">
          {children}
        </main>
        {/* {children} */}
      </body>
    </html>
  );
}
